config/routes.rb
get 'projects/:id/webhook_settings/show', :controller => 'webhook_settings', :action => 'show', :as => :show_webhook_settings
post 'projects/:id/webhook_settings/create', :controller => 'webhook_settings', :action => 'create', :as => :create_webhook
put 'projects/:id/webhook_settings/:webhook_id', :controller => 'webhook_settings', :action => 'update', :as => :update_webhook
delete 'projects/:id/webhook_settings/:webhook_id', :controller => 'webhook_settings', :action => 'destroy', :as => :delete_webhook

app/models/webhook.rb
class Webhook < ActiveRecord::Base
  unloadable
  belongs_to :project
end

app/controllers/webhook_settings_controller.rb
class WebhookSettingsController < ApplicationController
  before_filter :find_project, :authorize
  
  def create
    webhook = Webhook.new(:project_id => @project.id)
    webhook.url = params[:url]
    if webhook.save
      flash[:notice] = l(:notice_successful_create_webhook)
    else
      flash[:error] = l(:notice_fail_create_webhook)
    end
    redirect_to settings_project_path(@project, :tab => 'webhook')
  end
  def update
    id = params[:webhook_id]
    webhook = Webhook.where(:project_id => @project.id).where(:id => id).first
    webhook.url = params[:url]
    if webhook.save
      flash[:notice] = l(:notice_successful_update_webhook)
    else
      flash[:error] = l(:notice_fail_update_webhook)
    end
    redirect_to settings_project_path(@project, :tab => 'webhook')
  end
  def destroy
    id = params[:webhook_id]
    webhook = Webhook.where(:project_id => @project.id).where(:id => id).first
    if webhook.destroy
      flash[:notice] = l(:notice_successful_delete_webhook)
    else
      flash[:error] = l(:notice_fail_delete_webhook)
    end
    redirect_to settings_project_path(@project, :tab => 'webhook')
  end
end

app/views/webhook_settings/_show.html.erb
<% if User.current.allowed_to?( :manage_hook, @project) %>
<% if Webhook.where(:project_id => @project.id).first%>
<div class="box tabular">
<% Webhook.where(:project_id => @project.id).each do |webhook|%>
<%= form_tag(update_webhook_path(@project, webhook.id), :method => :put, :class => "tabular") do %>
<span>
  <span><strong>URL</strong></span>
  <%= text_field_tag :url, webhook.url, :size => 80 %>
  <%= submit_tag l(:button_update) %>
</span>
<% end %>
<%= link_to "Delete", delete_webhook_path(@project, webhook.id), :class => "icon icon-del", :method => :delete, :confirm => "Are you sure ?" %>
</br>
<% end %>
</div>
<% end %>
<%= form_tag(create_webhook_path(@project), :method => :post, :class => "tabular") do %>
<div class="box tabular">
<span>
  <span><strong>URL</strong></span>
  <%= text_field_tag :url, '', :size => 80 %>
  <%= submit_tag l(:button_add) %>
</span>
</div>


<% end %>

<% end %>